# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=False)),
                ('meta', models.TextField(default=b'{}')),
                ('username', models.CharField(max_length=63, unique=True)),
                ('companies', models.ManyToManyField(related_name='tagged_by', to='company.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
